### ISSUE TITLE
Tuple gist and Str are LTA

### ISSUE THREAD

**Issue by 0racle** [lizmat/Tuple#2]
The `gist` output has `.IterationBuffer` appended, and the `Str` output looks like a `.WHICH`

```perl-6
say Tuple.new(1, 2);  # (1, 2).IterationBuffer
put Tuple.new(1, 2);  # Tuple<61569856>
```

Not urgent... Thanks.

**Comment by lizmat** [comment]
Version 0.0.8 on its way to the ecosystem.  Thanks for the nudge!
